/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowGT (void);
GtkWidget* create_windowL (void);
GtkWidget* create_windowA (void);
GtkWidget* create_windowM (void);
GtkWidget* create_windowN (void);
GtkWidget* create_windowS (void);
GtkWidget* create_gestionabsence (void);
GtkWidget* create_window1y (void);
GtkWidget* create_window2y (void);
GtkWidget* create_ykcapteur (void);
