/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ADbottonaddclient (void)
{
  GtkWidget *ADbottonaddclient;
  GtkWidget *fixed1;
  GtkWidget *labelAjouter;
  GtkWidget *entrynom;
  GtkWidget *entryidentifiant;
  GtkWidget *entry3;
  GtkWidget *entrydatenaissance;
  GtkWidget *entryadresse;
  GtkWidget *entrybesoins;
  GtkWidget *labelnom;
  GtkWidget *labelidentifiant;
  GtkWidget *labelnumero;
  GtkWidget *labeldatenaissance;
  GtkWidget *labeladresse;
  GtkWidget *labelbesoin;
  GtkWidget *buttonajouter;
  GtkWidget *labelajouter;

  ADbottonaddclient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ADbottonaddclient), _("ADbottonaddclient"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (ADbottonaddclient), fixed1);

  labelAjouter = gtk_label_new (_("Ajouter un client"));
  gtk_widget_show (labelAjouter);
  gtk_fixed_put (GTK_FIXED (fixed1), labelAjouter, 152, 8);
  gtk_widget_set_size_request (labelAjouter, 168, 40);

  entrynom = gtk_entry_new ();
  gtk_widget_show (entrynom);
  gtk_fixed_put (GTK_FIXED (fixed1), entrynom, 120, 56);
  gtk_widget_set_size_request (entrynom, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynom), 8226);

  entryidentifiant = gtk_entry_new ();
  gtk_widget_show (entryidentifiant);
  gtk_fixed_put (GTK_FIXED (fixed1), entryidentifiant, 152, 104);
  gtk_widget_set_size_request (entryidentifiant, 176, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidentifiant), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed1), entry3, 152, 152);
  gtk_widget_set_size_request (entry3, 168, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entrydatenaissance = gtk_entry_new ();
  gtk_widget_show (entrydatenaissance);
  gtk_fixed_put (GTK_FIXED (fixed1), entrydatenaissance, 160, 200);
  gtk_widget_set_size_request (entrydatenaissance, 192, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrydatenaissance), 8226);

  entryadresse = gtk_entry_new ();
  gtk_widget_show (entryadresse);
  gtk_fixed_put (GTK_FIXED (fixed1), entryadresse, 152, 256);
  gtk_widget_set_size_request (entryadresse, 272, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryadresse), 8226);

  entrybesoins = gtk_entry_new ();
  gtk_widget_show (entrybesoins);
  gtk_fixed_put (GTK_FIXED (fixed1), entrybesoins, 128, 312);
  gtk_widget_set_size_request (entrybesoins, 536, 80);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrybesoins), 8226);

  labelnom = gtk_label_new (_("nom :"));
  gtk_widget_show (labelnom);
  gtk_fixed_put (GTK_FIXED (fixed1), labelnom, 0, 48);
  gtk_widget_set_size_request (labelnom, 104, 32);

  labelidentifiant = gtk_label_new (_("identifiant (cin):"));
  gtk_widget_show (labelidentifiant);
  gtk_fixed_put (GTK_FIXED (fixed1), labelidentifiant, 24, 96);
  gtk_widget_set_size_request (labelidentifiant, 120, 32);

  labelnumero = gtk_label_new (_("numero:"));
  gtk_widget_show (labelnumero);
  gtk_fixed_put (GTK_FIXED (fixed1), labelnumero, 8, 144);
  gtk_widget_set_size_request (labelnumero, 96, 24);

  labeldatenaissance = gtk_label_new (_("date de naissance:"));
  gtk_widget_show (labeldatenaissance);
  gtk_fixed_put (GTK_FIXED (fixed1), labeldatenaissance, 24, 192);
  gtk_widget_set_size_request (labeldatenaissance, 128, 32);

  labeladresse = gtk_label_new (_("adresse:"));
  gtk_widget_show (labeladresse);
  gtk_fixed_put (GTK_FIXED (fixed1), labeladresse, 0, 248);
  gtk_widget_set_size_request (labeladresse, 112, 24);

  labelbesoin = gtk_label_new (_("besoins :"));
  gtk_widget_show (labelbesoin);
  gtk_fixed_put (GTK_FIXED (fixed1), labelbesoin, 8, 304);
  gtk_widget_set_size_request (labelbesoin, 104, 24);

  buttonajouter = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (buttonajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonajouter, 280, 400);
  gtk_widget_set_size_request (buttonajouter, 88, 32);

  labelajouter = gtk_label_new (_("ajouter"));
  gtk_widget_show (labelajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), labelajouter, 104, 456);
  gtk_widget_set_size_request (labelajouter, 424, 56);

  g_signal_connect ((gpointer) buttonajouter, "clicked",
                    G_CALLBACK (on_buttonajouter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ADbottonaddclient, ADbottonaddclient, "ADbottonaddclient");
  GLADE_HOOKUP_OBJECT (ADbottonaddclient, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (ADbottonaddclient, labelAjouter, "labelAjouter");
  GLADE_HOOKUP_OBJECT (ADbottonaddclient, entrynom, "entrynom");
  GLADE_HOOKUP_OBJECT (ADbottonaddclient, entryidentifiant, "entryidentifiant");
  GLADE_HOOKUP_OBJECT (ADbottonaddclient, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (ADbottonaddclient, entrydatenaissance, "entrydatenaissance");
  GLADE_HOOKUP_OBJECT (ADbottonaddclient, entryadresse, "entryadresse");
  GLADE_HOOKUP_OBJECT (ADbottonaddclient, entrybesoins, "entrybesoins");
  GLADE_HOOKUP_OBJECT (ADbottonaddclient, labelnom, "labelnom");
  GLADE_HOOKUP_OBJECT (ADbottonaddclient, labelidentifiant, "labelidentifiant");
  GLADE_HOOKUP_OBJECT (ADbottonaddclient, labelnumero, "labelnumero");
  GLADE_HOOKUP_OBJECT (ADbottonaddclient, labeldatenaissance, "labeldatenaissance");
  GLADE_HOOKUP_OBJECT (ADbottonaddclient, labeladresse, "labeladresse");
  GLADE_HOOKUP_OBJECT (ADbottonaddclient, labelbesoin, "labelbesoin");
  GLADE_HOOKUP_OBJECT (ADbottonaddclient, buttonajouter, "buttonajouter");
  GLADE_HOOKUP_OBJECT (ADbottonaddclient, labelajouter, "labelajouter");

  return ADbottonaddclient;
}

